title: Amar Afifi
description: Chemical Processing Engineer
author: Amar Afifi
logo: ceee.png
github: https://github.com/amar3
about: Chemical Processing Engineer
disqus_shortname: amar3
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
    - text: Resume
      url: /resume/
      icon: fa-mortar-board
    - text: Projects
      url: /projects/
      icon: fa-gears
    - text: Contact
      url: /contact/
      icon: fa-envelope

url: "http://amar3.github.io/mywebsite"
baseurl: "/mywebsite"

enableTags: true
tagarray: []
