title: Amar Afifi
description: Hardware & Software Developer
author: Amar Afifi
logo: ieee2.svg
github: https://github.com/amar3
about: HW & SW Developer
disqus_shortname: amar3
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
    - text: Resume
      url: /resume/
      icon: fa-mortar-board
    - text: Projects
      url: /projects/
      icon: fa-gears
    - text: Contact
      url: /contact/
      icon: fa-envelope


social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-github
      link: '#'


share:
  twitter_username: \#
  fb_appid: 000000000000

url: "http://amar3.github.io/mywebsite"
baseurl: "/mywebsite"

enableTags: true
tagarray: []
